apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-pipeline-run
spec:
  pipelineRef:
    name: build-pipeline
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: workspace-pvc
  params:
    - name: image
      value: jfcoronado/go-sample-app:2020.06.22-11.41.28
    - name: repo-url
      value: https://github.com/springone-tour-2020-cicd/go-sample-app.git
    - name: revision
      value: master
  serviceAccountName: build-bot
